FROM python:3.13-slim
WORKDIR /app

COPY pyproject.toml README.md ./
COPY shared ./shared
RUN pip install --no-cache-dir .

COPY apps ./apps

EXPOSE 8000
CMD ["uvicorn", "apps.API.main:app", "--host", "0.0.0.0", "--port", "8000"]
