class ConfigClave:
    SETUP_COMPLETADO = "SETUP_COMPLETADO"
    NOMBRE_EMPRESA = "NOMBRE_EMPRESA"
    NIT = "NIT"
    ZONA_HORARIA = "ZONA_HORARIA"
    IDIOMA = "IDIOMA"
    TOLERANCIA_MIN = "TOLERANCIA_MIN"
    QR_EXPIRACION_SEG = "QR_EXPIRACION_SEG"
    EXIGIR_CODIGO = "EXIGIR_CODIGO"
